# Generated by Django 3.2.9 on 2021-11-23 05:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.CharField(max_length=32)),
                ('type', models.CharField(max_length=16)),
                ('objtype', models.CharField(max_length=16)),
                ('object', models.CharField(max_length=32)),
                ('details', models.TextField()),
            ],
        ),
    ]
